"""
DAG: raw_orders_ingestion
Generated by DataDoc from DataHub metadata for dataset:
  urn:li:dataset:(urn:li:dataPlatform:snowflake,analytics.raw_orders,PROD)

DataHub context used:
  - Schema (analytics.raw_orders, Snowflake):
      order_id            varchar   Primary key
      customer_id         varchar   FK to customers table
      order_total_cents   bigint    Order total in cents
      placed_at           timestamp When the order was placed
      region              varchar   Sales region
      status              varchar   Order status: pending, shipped, cancelled, test
  - Description: "Raw customer orders, loaded from the checkout service."
  - Upstream lineage: none registered in DataHub (source is the external
    checkout service, not itself a cataloged dataset) -> this DAG performs
    the extract-from-source step for that reason.
  - Downstream lineage: analytics.weekly_revenue_report ("Certified weekly
    revenue rollup used by Finance"), a Dashboard-subtype dataset with
    health status PASS.
  - Owners / tags / glossary terms: none currently registered on the
    dataset in DataHub.

Schedule rationale:
  raw_orders is a raw ingestion table with no upstream lineage recorded
  (it is loaded from an external operational system, the checkout
  service). Its sole known downstream consumer, weekly_revenue_report,
  is a weekly Finance rollup. To guarantee that rollup always has a full,
  up-to-date week of data behind it (and to keep failure blast radius to
  a single day rather than a week), this DAG ingests incrementally once
  per day, well ahead of any weekly downstream run.

Retry rationale:
  Extraction talks to an external operational service (checkout service)
  over the network, which is more failure-prone than an intra-warehouse
  transform. retries=3 with exponential backoff (starting at 5 minutes)
  is used to ride out transient upstream outages without paging anyone
  for a single blip.
"""
from __future__ import annotations

import logging
from datetime import datetime, timedelta

from airflow.decorators import dag, task
from airflow.providers.snowflake.hooks.snowflake import SnowflakeHook

logger = logging.getLogger(__name__)

CHECKOUT_SERVICE_CONN_ID = "checkout_service_api"
SNOWFLAKE_CONN_ID = "snowflake_default"
TARGET_TABLE = "analytics.raw_orders"

# Columns as documented in DataHub for analytics.raw_orders.
RAW_ORDERS_COLUMNS = [
    "order_id",
    "customer_id",
    "order_total_cents",
    "placed_at",
    "region",
    "status",
]

default_args = {
    "owner": "data-engineering",  # no owner registered in DataHub; using team default
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
    "retry_exponential_backoff": True,
    "max_retry_delay": timedelta(minutes=30),
}


@dag(
    dag_id="raw_orders_ingestion",
    description=(
        "Extracts orders from the checkout service and loads them into "
        "analytics.raw_orders (Snowflake), the raw source feeding the "
        "Finance weekly_revenue_report rollup."
    ),
    schedule="@daily",
    start_date=datetime(2025, 1, 1),
    catchup=False,
    max_active_runs=1,
    default_args=default_args,
    tags=["analytics", "orders", "snowflake", "checkout-service"],
)
def raw_orders_ingestion():
    @task
    def extract_orders(data_interval_start=None, data_interval_end=None) -> list[dict]:
        """Pull new/updated orders from the checkout service for this interval."""
        from airflow.providers.http.hooks.http import HttpHook

        hook = HttpHook(method="GET", http_conn_id=CHECKOUT_SERVICE_CONN_ID)
        response = hook.run(
            endpoint="/v1/orders",
            data={
                "placed_after": data_interval_start.isoformat(),
                "placed_before": data_interval_end.isoformat(),
            },
        )
        response.raise_for_status()
        orders = response.json()
        logger.info("Extracted %d orders from checkout service", len(orders))
        return orders

    @task
    def validate_and_shape(raw_orders: list[dict]) -> list[dict]:
        """Keep only the documented analytics.raw_orders columns, in order."""
        shaped = []
        for record in raw_orders:
            missing = [c for c in RAW_ORDERS_COLUMNS if c not in record]
            if missing:
                logger.warning(
                    "Skipping order %s: missing expected columns %s",
                    record.get("order_id", "<unknown>"),
                    missing,
                )
                continue
            shaped.append({col: record[col] for col in RAW_ORDERS_COLUMNS})
        logger.info("Validated %d/%d orders", len(shaped), len(raw_orders))
        return shaped

    @task
    def load_to_snowflake(orders: list[dict]) -> int:
        """Upsert (MERGE) validated orders into analytics.raw_orders by order_id."""
        if not orders:
            logger.info("No orders to load; skipping merge.")
            return 0

        hook = SnowflakeHook(snowflake_conn_id=SNOWFLAKE_CONN_ID)
        staging_table = f"{TARGET_TABLE}_staging"

        rows = [tuple(order[col] for col in RAW_ORDERS_COLUMNS) for order in orders]
        columns_sql = ", ".join(RAW_ORDERS_COLUMNS)
        placeholders = ", ".join(["%s"] * len(RAW_ORDERS_COLUMNS))

        create_staging_sql = f"""
            CREATE OR REPLACE TEMPORARY TABLE {staging_table} LIKE {TARGET_TABLE};
        """
        insert_staging_sql = f"""
            INSERT INTO {staging_table} ({columns_sql})
            VALUES ({placeholders});
        """
        merge_sql = f"""
            MERGE INTO {TARGET_TABLE} AS target
            USING {staging_table} AS source
            ON target.order_id = source.order_id
            WHEN MATCHED THEN UPDATE SET
                customer_id = source.customer_id,
                order_total_cents = source.order_total_cents,
                placed_at = source.placed_at,
                region = source.region,
                status = source.status
            WHEN NOT MATCHED THEN INSERT ({columns_sql})
            VALUES ({", ".join(f"source.{c}" for c in RAW_ORDERS_COLUMNS)});
        """

        conn = hook.get_conn()
        cursor = conn.cursor()
        try:
            cursor.execute(create_staging_sql)
            cursor.executemany(insert_staging_sql, rows)
            cursor.execute(merge_sql)
            conn.commit()
        finally:
            cursor.close()
            conn.close()

        logger.info("Merged %d orders into %s", len(rows), TARGET_TABLE)
        return len(rows)

    raw = extract_orders()
    shaped = validate_and_shape(raw)
    load_to_snowflake(shaped)


raw_orders_ingestion()
