-- Generated by DataDoc from DataHub metadata for `analytics.raw_orders`
--
-- DataHub context used:
--   schema:  order_id (varchar), customer_id (varchar), status (varchar),
--            order_total_cents (bigint), placed_at (timestamp), region (varchar)
--   lineage: upstream of `analytics.weekly_revenue_report` (Finance, certified)
--   glossary: `region` tagged with term "Sales Region"; no PII columns found

with source as (
    select * from {{ source('raw', 'orders') }}
),

renamed as (
    select
        order_id,
        customer_id,
        status,
        order_total_cents / 100.0 as order_total,
        placed_at,
        region
    from source
    where status not in ('cancelled', 'test')
)

select * from renamed
