-- Migration: Add discount_cents to analytics.raw_orders
-- Generated by DataDoc using live DataHub context.
--
-- DataHub context used (urn:li:dataset:(urn:li:dataPlatform:snowflake,analytics.raw_orders,PROD)):
--   Description: "Raw customer orders, loaded from the checkout service."
--   Existing columns (verified via schemaMetadata, none invented):
--     - customer_id        varchar   NOT NULL  "FK to customers table"
--     - order_id            varchar   NOT NULL  "Primary key"
--     - order_total_cents   bigint    NOT NULL  "Order total in cents"
--     - placed_at           timestamp NOT NULL  "When the order was placed"
--     - region              varchar   NOT NULL  "Sales region"
--     - status              varchar   NOT NULL  "Order status: pending, shipped, cancelled, test"
--   Upstream lineage: none registered in DataHub for this dataset.
--   Downstream lineage: analytics.weekly_revenue_report (Finance's certified weekly revenue rollup) -
--     this migration is additive/backward-compatible so that downstream model is unaffected.
--   Owners: none currently assigned in DataHub.
--   Tags / glossary terms: none currently assigned in DataHub.
--
-- New column mirrors the existing cents convention used by order_total_cents (bigint, cents-denominated).
-- Defaulted to 0 and kept NOT NULL so existing rows and the downstream revenue rollup remain valid
-- without a backfill step.

-- +migrate Up
ALTER TABLE analytics.raw_orders
  ADD COLUMN discount_cents BIGINT NOT NULL DEFAULT 0
  COMMENT 'Discount amount applied to the order, in cents. Added to support the promo feature.';

-- +migrate Down
ALTER TABLE analytics.raw_orders
  DROP COLUMN discount_cents;
